name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy_to_dockerhub:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug username
        run: echo "Username is ${{ secrets.DOCKER_USERNAME }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-task3:latest .

      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/docker-task3:latest ${{ secrets.DOCKER_USERNAME }}/docker-task3:${{ github.sha }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-task3:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-task3:${{ github.sha }}
      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
                server_address: smtp.gmail.com
                server_port: 465
                username: ${{ secrets.EMAIL_USERNAME }}
                password: ${{ secrets.EMAIL_PASSWORD }}
                subject: "CI Pipeline Status: ${{ job.status }}"
                to: ${{ secrets.EMAIL_TO }}
                from: ${{ secrets.EMAIL_USERNAME }}
                body: "Pipeline finished with status: ${{ job.status }}"
